### ISSUE TITLE
Ruby version required 2.6.2

### ISSUE THREAD

**Issue by sethkane** [chiefkikio/AFutureDate#2]
I currently have Ruby 2.6.3 and it is throwing an error that I need 2.6.2
Is there a way to get it to use your version or newer?

![image](https://user-images.githubusercontent.com/2932427/78793304-d3d14d80-7977-11ea-96a3-09b6c1ad528d.png)

https://github.com/chiefkikio/AFutureDate/blob/3c3dc17f869e4196448aea0936c704fe9d47fe40/Gemfile#L2

**Comment by chiefkikio** [comment]
I use rvm to manage ruby versions but we can update it to use 2.6.3 too. To be super honest, I very arbitrarily chose a version higher than 2.4 :P

**Comment by sethkane** [comment]
I installed RVM but I would add that to your Readme so other users know they might have to use it.
